# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/6_xianyu/22_jesd_udp/code/V7_204b_1/V7_204b.srcs/sources_1/ip/fifo_4096x32/fifo_4096x32.xci
# IP: The module: 'fifo_4096x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/6_xianyu/22_jesd_udp/code/V7_204b_1/V7_204b.gen/sources_1/ip/fifo_4096x32/fifo_4096x32.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_4096x32'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/6_xianyu/22_jesd_udp/code/V7_204b_1/V7_204b.gen/sources_1/ip/fifo_4096x32/fifo_4096x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_4096x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/6_xianyu/22_jesd_udp/code/V7_204b_1/V7_204b.srcs/sources_1/ip/fifo_4096x32/fifo_4096x32.xci
# IP: The module: 'fifo_4096x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/6_xianyu/22_jesd_udp/code/V7_204b_1/V7_204b.gen/sources_1/ip/fifo_4096x32/fifo_4096x32.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_4096x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/6_xianyu/22_jesd_udp/code/V7_204b_1/V7_204b.gen/sources_1/ip/fifo_4096x32/fifo_4096x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_4096x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
