# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/maoxi/Desktop/CUHKProject/Ultrasonic/Kintex7/Code/V7_204b_2/V7_204b.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_1/design_1_jesd204_0_1.xci
# IP: The module: 'design_1_jesd204_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/maoxi/Desktop/CUHKProject/Ultrasonic/Kintex7/Code/V7_204b_2/V7_204b.gen/sources_1/bd/design_1/ip/design_1_jesd204_0_1/synth/design_1_jesd204_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_jesd204_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/maoxi/Desktop/CUHKProject/Ultrasonic/Kintex7/Code/V7_204b_2/V7_204b.gen/sources_1/bd/design_1/ip/design_1_jesd204_0_1/synth/design_1_jesd204_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_jesd204_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/maoxi/Desktop/CUHKProject/Ultrasonic/Kintex7/Code/V7_204b_2/V7_204b.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_1/design_1_jesd204_0_1.xci
# IP: The module: 'design_1_jesd204_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/maoxi/Desktop/CUHKProject/Ultrasonic/Kintex7/Code/V7_204b_2/V7_204b.gen/sources_1/bd/design_1/ip/design_1_jesd204_0_1/synth/design_1_jesd204_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_jesd204_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/maoxi/Desktop/CUHKProject/Ultrasonic/Kintex7/Code/V7_204b_2/V7_204b.gen/sources_1/bd/design_1/ip/design_1_jesd204_0_1/synth/design_1_jesd204_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_jesd204_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
