# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_jesd204_0_0/design_1_jesd204_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_jesd204_0_0 || ORIG_REF_NAME==design_1_jesd204_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_jesd204_0_1/design_1_jesd204_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_jesd204_0_1 || ORIG_REF_NAME==design_1_jesd204_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_jesd204_phy_0_0/design_1_jesd204_phy_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_jesd204_phy_0_0 || ORIG_REF_NAME==design_1_jesd204_phy_0_0} -quiet] -quiet

# IP: ip_rtl/RTL8211_Config_IP_0/RTL8211_Config_IP_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RTL8211_Config_IP_0 || ORIG_REF_NAME==RTL8211_Config_IP_0} -quiet] -quiet

# XDC: c:/Users/maoxi/Desktop/CUHKProject/Ultrasonic/Kintex7/Code/V7_204b_2/V7_204b.gen/sources_1/bd/design_1/design_1_ooc.xdc
